name: Dynhut
version: '${project.version}'
description: Use dynmap on Minehut using ngrok
main: be.mrtibo.dynhut.Dynhut
api-version: 1.19
depend:
  - dynmap
commands:
  map:
    description: Get the public ngrok url of the map
    usage: /map
  dynhut:
    description: Retry starting the ngrok process
    usage: /dynhut
    permission: dynhut.admin
permissions:
  dynhut.admin:
    default: op